### PR TITLE
Navbar added to other pages

### LINKED ISSUE #2: add the navbar present in home page of website to all other pages

### PR DESCRIPTION
**Pull request by unnikrishnan2002**
closed #2 

Navbar is added to all other pages + background color of the navbar is changed

### CODE REVIEW

**Comment by unnikrishnan2002** [comment]
I found an issue with the css of the navbar . So when I copied the css from the main css file and pasted it to the css of `30 days of code` and `collaborators` it hinders with the css of those pages and looks something like this

image

**Comment by arpit456jain** [comment]
leave it on those page @unnikrishnan2002

**Comment by unnikrishnan2002** [comment]
> leave it on those page @unnikrishnan2002

I have pushed it anyway so I guess it's fine if it's like that .

**Comment by arpit456jain** [comment]
yeah its fine for now

**Comment by arpit456jain** [comment]
hey please add it to all pages 

click one MMMUT inside that there are lots of folder check them

**Comment by unnikrishnan2002** [comment]
> hey please add it to all pages
> 
> click one MMMUT inside that there are lots of folder check them

Oops sorry I didn't checked that . I will add them👍

**Comment by arpit456jain** [comment]
hey @unnikrishnan2002 i am merging this PR u can make a another PR if u want

**Pull request merged**
