### PR TITLE
fix Navbar

### PR DESCRIPTION
**Pull request by 7ORP3DO**
Related Issue : #15

### CODE REVIEW

**Comment by arpit456jain** [comment]
@7ORP3DO  did u check the website after changes

https://deploy-preview-21--study-material-all-in-one.netlify.app/

**Comment by 7ORP3DO** [comment]
> @7ORP3DO did u check the website after changes
> 
> https://deploy-preview-21--study-material-all-in-one.netlify.app/

Yes bro i did check everything is working properly.  If something looks wrong you can tell me, I'll try to fix.

**Comment by arpit456jain** [comment]
@7ORP3DO u just add the simple bootstrap navbar in it and its looks horrible 
image

**Comment by 7ORP3DO** [comment]
> @7ORP3DO u just add the simple bootstrap navbar in it and its looks horrible image

Sorry I forgot about other elements.  I thought it was already like this.  Boostrap navbars are reponsive and easy to use so i thought it would be right to use them.

**Comment by arpit456jain** [comment]
the bug is fixed

**Pull request closed without merging**
